# fly.toml app configuration file generated for neo4j-webapp on 2025-07-04T13:45:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'neo4j-webapp'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
