services:
  neo4j:
    image: neo4j:5.19-community
    container_name: neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/Testing123!
      FLASK_APP: app.py
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt protocol
    volumes:
      - neo4j_data:/data

  python-app:
    build:
      context: .
    container_name: python-app
    restart: unless-stopped
    init: true
    ports:
      - "5050:5000"
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: Testing123!
      NEO4J_DATABASE: KG2



    # If you want to override .env values, add them here
volumes:
  neo4j_data:

